### ISSUE TITLE
Can't install the tool

### ISSUE THREAD

**Issue by ChoppinBlockParty** [google/yamlfmt#96] opened 2023-03-22 15:38 UTC
```
go get github.com/google/yamlfmt/cmd/yamlfmt@latest
build github.com/google/yamlfmt/cmd/yamlfmt: cannot load io/fs: malformed module path "io/fs": missing dot in first path element
```

Go version 13.

**Comment by braydonk** [comment] 2023-03-22 15:49
Thanks for making an issue!

2 things with this:

First, by "Go Version 13", are you referring to version 1.13? This version is unfortunately too old to build `yamlfmt` from source. In the [go.mod](https://github.com/google/yamlfmt/blob/main/go.mod) you can see the version restriction. Building `yamlfmt` requires go 1.20.  

Second, `github.com/google/yamlfmt/cmd/yamlfmt` is not a module. It's a sub-package of the main module that is used to build the executable. That's why the `go install` instructions in the README refer to `github.com/google/yamlfmt/cmd/yamlfmt`; it's building and installing the binary. To use this `go get` method, you will need to get the main module, `go get github.com/google/yamlfmt@latest`. However, in a new enough Go version, `go get` by default does not build the modules anyway, and won't install it.

I will close this issue since this is working as intended; if you have trouble installing with go 1.20, feel free to re-open.

**Closed by braydonk** 2023-03-22 15:49 UTC
